import os
import sys
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns

# Add parent directory to path so we can import models
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from models.fall_detector import FallDetector
from models.hr_anomaly import HRAnomalyDetector

def generate_training_data():
    """Load synthetic data generated by simulator."""
    data_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "synthetic", "synthetic_dataset.csv")
    if not os.path.exists(data_path):
        print(f"Error: Training data not found at {data_path}")
        print("Please run sensor_simulator.py first.")
        sys.exit(1)
        
    df = pd.read_csv(data_path)
    print(f"Loaded {len(df)} records for training.")
    return df

def train_fall_detector(df):
    print("\n--- Training Fall Detector ---")
    
    # Feature extraction
    # Simplified: using raw accel data for training here. In a real scenario, 
    # we would apply sliding window feature extraction.
    X = []
    y = df['is_fall'].values
    
    detector = FallDetector()
    for _, row in df.iterrows():
        features = detector.extract_features(row['accel_x'], row['accel_y'], row['accel_z'])
        X.append(features)
        
    X = np.array(X)
    
    # Split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
    
    print(f"Training on {len(X_train)} samples, testing on {len(X_test)} samples.")
    print(f"Class distribution - SAFE: {sum(y_train==0)}, FALL: {sum(y_train==1)}")
    
    # Check if we have enough falls to train
    if sum(y_train==1) < 5:
        print("Warning: Not enough fall samples to train SVM effectively. Using rule-based only for now.")
        detector.is_trained = False
        return detector
    
    # Train
    detector.fit(X_train, y_train)
    
    # Evaluate
    y_pred = detector.model.predict(X_test)
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=["SAFE", "FALL"]))
    
    # Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=["SAFE", "FALL"], yticklabels=["SAFE", "FALL"])
    plt.title('Fall Detection Confusion Matrix')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    
    models_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "models")
    plt.savefig(os.path.join(models_dir, "fall_confusion_matrix.png"))
    print("Saved confusion matrix plot.")
    
    detector.save_model(os.path.join(models_dir, "fall_detector.joblib"))
    return detector

def train_hr_anomaly(df):
    print("\n--- Training HR Anomaly Detector ---")
    
    # Filter out obvious simulated anomalies to train the baseline Isolation Forest
    # In real world, IsolationForest expects mostly normal data
    # Here we just use the first 80% of data for training (unsupervised)
    X = []
    detector = HRAnomalyDetector()
    
    for hr in df['heart_rate'].values:
        features = detector.get_features(hr)
        detector.add_reading(hr)
        X.append(features)
        
    X = np.array(X)
    
    # Train on first 80%
    train_size = int(len(X) * 0.8)
    X_train = X[:train_size]
    X_test = X[train_size:]
    
    print(f"Training Isolation Forest on {len(X_train)} samples...")
    detector.fit(X_train)
    
    models_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "models")
    detector.save_model(os.path.join(models_dir, "hr_anomaly.joblib"))
    
    # Simple evaluation
    preds = detector.model.predict(X_test)
    anomalies = sum(preds == -1)
    print(f"Detected {anomalies} anomalies in {len(X_test)} test samples ({(anomalies/len(X_test))*100:.2f}%).")
    
    return detector

if __name__ == "__main__":
    print("Starting Phase 2 Model Training Pipeline...")
    df = generate_training_data()
    
    train_fall_detector(df)
    train_hr_anomaly(df)
    
    print("\nPhase 2 Training Complete!")
